intel/confidential-cloud-native-primitives

.github/workflows/pr-check-rust.yaml
the rust check will build the rust to a binary, 
so this PR will add the dependent libtdx-attest lib.
=> workflows/pr-check-rust.yaml: add dependency lib when do rust check

.github/workflows/pr-container-check.yaml, .github/workflows/pr-license-python.yaml
all none Intel or hardware dependent jobs should all run in GitHub hosted runner
=> workflows: update to use github hosted runner

chart/eventlog-server/Chart.yaml, chart/eventlog-server/templates/NOTES.txt, chart/eventlog-server/templates/_helpers.tpl, chart/eventlog-server/templates/daemonset.yaml, chart/eventlog-server/templates/namespace.yaml, chart/eventlog-server/templates/serviceaccount.yaml, chart/eventlog-server/values.yaml
Add helm chart for the eventlog-server service for deployment, including such components:
- namespace
- daemonset
- serviceaccount
Skip service support for now, as we are using UDS for connection
resolves #20
=> service/eventlog-server: add helm chart

device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/daemonset.yaml, device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/values.yaml, device-plugin/ccnp-device-plugin/pkg/server/server.go
This PR will add an init container to detect the TDX version in runtime and let ccnp device plugin to register device node to Kubernetes accordingly
=> ccnp-device-plugin: add init container to detect TDX version

.github/workflows/publish-ccnp.yaml, sdk/python3/.gitignore
This action will help to publish the CCNP project to pypi.org
https://pypi.org/manage/project/ccnp
=> action: add action to publish the CCNP to PyPI

.github/workflows/pr-check-rust.yaml, service/quote-server/README.md
this PR contains fix for:
- pr-check-rust.yaml: use rust 1.70.0 as per required by rust deny
- README.md: fix image name
=> quote-server: use rust 1.70.0 as per required by rust deny

service/quote-server/src/tee.rs
coming in nonce string is base64 encoded to be sync with SDK, quote server will decode before use
=> quote-server: update nonce handling

sdk/python3/README.md, sdk/python3/ccnp/quote/quote_sdk.py, sdk/python3/pyproject.toml
- Add quote usage example for SDK, update some descriptions
- Bump version to 0.0.2
=> doc: update the readme of SDK and bump version to 0.0.2

container/quote-server/Dockerfile, deployment/charts/quote-server/Chart.yaml, deployment/charts/quote-server/templates/NOTES.txt, deployment/charts/quote-server/templates/_helpers.tpl, deployment/charts/quote-server/templates/daemonset.yaml, deployment/charts/quote-server/templates/namespace.yaml, deployment/charts/quote-server/templates/serviceaccount.yaml, deployment/charts/quote-server/values.yaml, service/quote-server/README.md
This PR includes changes for:
- add helm templates and configurations for quote server daemonset deployment
- update quote server readme to introduce helm deploy method
=> quote-server: add support for helm deploy

service/quote-server/README.md
this PR update readme for quote server to prepare dependent directory if user try to run quote server binary directly
=> quote-server: add tips if run binary directly

container/quote-server/Dockerfile
this PR will update Dockerfile to use right USER ID to run quote server
=> quote-server: use ccnp as user to run quote server

service/quote-server/tdx_lib/src/tdx_lib.rs
This PR will fix bug in rust tdx lib to get tdreport and quote: the string slice will be updated to copy full array of report data, tdreport and other request headers
=> quote server: fix ioctl quote bug

service/quote-server/src/quote_server.rs, service/quote-server/tdx_lib/src/tdx_lib.rs
This PR will add 2 UT cases in TDX attestation lib and 1 UT case in quote server to verify report data in tdreport and quote is the same as passed in
=> quote server: add UT cased to verify report data in tdreport and quote

sdk/python3/ccnp/quote/quote_sdk.py
cert_data should be assigned to class member
=> python SDK: fix bug in quote server python SDK

device-plugin/ccnp-device-plugin/README.md
This PR updates ccnp device plugin doc for:
- TDX 1.5 support for tdx device node permission setting
- auto creation of UDS dir with correct permission
- 
=> ccnp-device-plugin: update documentation

.gitignore, tools/cvm-image-rewriter/pre-stage/04-user-authkey/host_run.sh
Config ssh authorized key for user $CVM_USER.
By default password login is disabled.
When $CVM_AUTH_KEY is not set, this unit will not run.
=> cvm-guest-rewriter: configure user login key

tools/cvm-image-rewriter/run.sh
when running the virt-customize, it need read permission on /boot/vmlinuz-$(uname -r) so check the read permission firstly.
=> run.sh: check whether current user has permission on kernel image

deployment/manifests/eventlog-server-deployment.yaml
Add node selector to deploy eventlog server on TDX enabled node only
=> eventlog-server-deployment.yaml: Add node selector

tools/cvm-image-rewriter/pre-stage/07-install-mvp-guest/README.md, tools/cvm-image-rewriter/pre-stage/07-install-mvp-guest/host_run.sh
This unit requires the environment variable CVM_MVP_GUEST_REPO.
It will copy the local repo CVM_MVP_GUEST_REPO to guest and then install the TDX kernel.
=> cvm-image-rewriter: add 07-install-mvp-guest

sdk/python3/README.md
Update the example usage of quote SDK，otherwise it will cause failure to get quote：
`details = "[get_tdx_quote]: [generate_tdx_report_data] nonce is not base64 encoded: InvalidByte(23, 45)"`
=> sdk/python/README.md: Update the example usage of quote SDK

README.md
To align with CII-Best-Practices in OpenSSF, register the project and adding badge for it.
=> Doc: add OpenSSF badge in README

README.md
1. Move design section to wiki
2. Add recommended configuration in installation section
3. Other small adjustment
=> README.md: refine readme
