intel/confidential-cloud-native-primitives

.github/cspell.json
.github/workflows/pr-doclint.yaml

This PR is to add doc lint in .github action to fix #3

.github/pr-doclint.yaml: add document lint scan CI

---

.github/workflows/pr-shell-check.yaml

Add Github action in CI to scan shell code, to fix #10

.github/pr-shell-check.yaml: add shell code scan in CI

---

.github/workflows/pr-check-rust.yaml

Add Rust code scan in Github action, for #23

.github/pr-check-rust.yaml: Add Rust code scan in CI

---

.github/workflows/pr-check-rust.yaml

Add api definitions (protobuf) for services including:
- eventlog-server
- measurement-server
- quote-server
resolves #12

api: add api definitions for the services

---

.github/workflows/pr-golanglint.yaml
.github/workflows/pr-shell-check.yaml

Add Golong lint for CI.
For #24

.github/pr-golanglint.yaml: Add Golong lint for CI

---

.github/workflows/pr-container-check.yaml
.github/workflows/pr-license-python.yaml

* add action for container build
* rename and add path filter for python license check
resolves #36

CI/CD: add action for container build

---

README.md

A Note of not production-ready disclaimer.

README.md: Add Notes at the bottom of README

---

.github/workflows/pr-check-rust.yaml

workflows/pr-check-rust.yaml: update lib install step due to build error

---

.github/workflows/pr-golanglint.yaml
.github/workflows/pr-pylint.yaml

* add filters for path and file extension to avoid unnecessary checks

CI/CD: further restrict github actions

---

container/build.sh
container/eventlog-server/Dockerfile

* Add the dockerfile for the eventlog-server service.
resolves #17

service/eventlog-server: add Dockerfile

---

.github/workflows/pr-check-rust.yaml

add quote server required lib for rust check as rust check need to build binary

workflows/pr-check-rust.yaml: add quote server required lib for rust check

---

.github/workflows/pr-golanglint.yaml

* add if condition for golanglint to run in correct directory

CI/CD: fix golanglint

---

.github/workflows/pr-golanglint.yaml

* add fetch depth setting for checkout action
* update version of changed-files action

fix: fix golang lint error

---

container/quote-server/Dockerfile

add Dockerfile to build docker image based on service/quote-server

service/quote-server: add Dockerfile

---

container/measurement-server/Dockerfile

* add dockerfile for the measurement-server service
resolves #18

service/measurement-server: add Dockerfile for the service

---

deployment/manifests/eventlog-server-deployment.yaml
deployment/manifests/measurement-server-deployment.yaml
deployment/manifests/namespace.yaml

* add deployment yaml for eventlog server service
* split ccnp namespace as separate deployment yaml that can be used for multiple services

deployment: add deployment yaml for eventlog and split namespace

---

service/eventlog-server/resources/tdx.go
service/eventlog-server/resources/tpm.go
service/eventlog-server/server/server.go
service/measurement-server/resources/base.go
service/measurement-server/resources/sev.go
service/measurement-server/resources/tdx.go
service/measurement-server/resources/tpm.go
service/measurement-server/server/server.go

* change the license format to the formal one
* remove and edit incorrect comments

fix: fix license format and clean up comments

---

.github/cspell.json
service/eventlog-server/README.md

* Add readme file for the eventlog-server service

Documentation: add readme file for eventlog-server

---

.github/cspell.json
service/measurement-server/README.md

documentation: add readme for measurement-server

---

container/build.sh

1. Change EIP_REGISTRY => CCNP_REGISTRY
2. Add comments for all functions in build.sh

container/build.sh: Update comments

---

service/eventlog-server/resources/tdx.go

* correct the wrong error message

fix: fix the wrong error message

---

deployment/manifests/quote-server-deployment.yaml
device-plugin/ccnp-device-plugin/README.md
device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/daemonset.yaml
service/quote-server/README.md

fix readme and template yaml for deployment

ccnp-device-plugin: fix readme and template yaml for deployment

---

service/measurement-server/go.mod
service/measurement-server/go.sum
service/measurement-server/resources/base.go
service/measurement-server/resources/base_test.go
service/measurement-server/resources/sev.go
service/measurement-server/resources/sev_test.go
service/measurement-server/resources/tdx.go
service/measurement-server/resources/tdx_test.go
service/measurement-server/resources/tpm.go
service/measurement-server/resources/tpm_test.go
service/measurement-server/server/server.go
service/measurement-server/server/server_test.go

* add unit test for measurement service
* gofmt files to fix format issues

service/measurement: add unit test

---

service/eventlog-server/resources/tdx.go
service/eventlog-server/resources/tdx_test.go
service/eventlog-server/resources/tpm.go
service/eventlog-server/resources/tpm_test.go
service/eventlog-server/server/server_test.go

* add unit tests for eventlog grpc server

service/eventlog-server: add unit test

---

service/quote-server/Cargo.toml
service/quote-server/src/quote_server.rs
service/quote-server/src/tee.rs

Add more test cases for:
- grpc server
- tee handling functions

service/quote-server: add more unit tests for quote server

---

device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/daemonset.yaml

ccnp-device-plugin: fix helm template format

---

.github/workflows/pr-pylint.yaml
sdk/python3/ccnp/measurement/measurement_sdk.py

* add input check for params
* add description for functions

sdk/get_measurement: add more input check and comments

---

sdk/python3/README.md

* Add the overall readme for ccnp sdk

Doc: add readme for ccnp sdk

---

device-plugin/ccnp-device-plugin/README.md

ccnp-device-plugin: add steps to import NFD images to containerd

---

service/quote-server/src/tee.rs

update TD report data creation logic

quote server: update TD report data creation logic

---

README.md

Add html doc entry in general readme file

Doc: add doc entry in README.

---

README.md
sdk/python3/README.md
service/quote-server/README.md

* Add more description and installation part for the readme
* Change the url for API doc

Doc: enhance main readme and some fixes

---

README.md

Make the corresponding change for golangci  badge

Fix: update readme with correct github action name

---

service/quote-server/src/quote_server.rs

give out detailed logs on UDS bind error on CCNP working directory /run/ccnp/uds of missing dir or wrong permission

quote-server: add detailed log for UDS bind error

---

.github/workflows/pr-check-rust.yaml

run UT and all rust checks in TDVM runner

quote server: run UT in TDVM runner

---

service/eventlog-server/server/server.go
service/measurement-server/server/server.go

Add MaxConcurrentStreams server option to mitigate resource drain attack on grpc server

Fix: mitigate risks for CVE-2023-44487

---

device-plugin/ccnp-device-plugin/pkg/server/server.go

ccnp-device-plugin: mitigate risks for CVE-2023-44487 with grpc lib

---

deployment/manifests/eventlog-server-deployment.yaml
deployment/manifests/measurement-server-deployment.yaml

Remove 'NET_RAW' capability from daemonset container

Fix: fix coverity issue

---

device-plugin/ccnp-device-plugin/deploy/helm/ccnp-device-plugin/templates/daemonset.yaml

tdx1.0 => tdx-guest
tdx1.5 => tdx_guest

fix the typo of tdx1.5 device node name in device-plugin

---

.github/cspell.json
.github/workflows/pr-container-check.yaml
container/build.sh
container/pccs/Dockerfile
container/pccs/README.md
container/pccs/default.json
container/pccs/network_setting.conf
container/pccs/pre-built.sh
container/qgs/Dockerfile
container/qgs/README.md
container/qgs/sgx_default_qcnl.conf

Add the Dockerfile of PCCS and QGS, also fix the build script bugs.
Note: move PCCS and QGS from tdx-tools to ccnp.

Add dockerlized PCCS and QGS service

---

deployment/manifests/eventlog-server-deployment.yaml
deployment/manifests/measurement-server-deployment.yaml
deployment/manifests/quote-server-deployment.yaml

Add CPU limit and memory limit to the containers in the YAML files.

Add CPU limit and memory limit

---

tools/cvm-image-rewriter/.gitignore
tools/cvm-image-rewriter/README.md
tools/cvm-image-rewriter/run.sh

If want to skip some steps, please create a file named "NOT_RUN" under the plugin directory. For example:
``touch pre-stage/01-resize-image/NOT_RUN``

run.sh: add capability to skip specific plugin if NOT_RUN found

---

tools/cvm-image-rewriter/pre-stage/08-device-permission/files/etc/udev/rules.d/90-tdx.rules
tools/cvm-image-rewriter/pre-stage/09-ccnp-uds-directory-permission/files/usr/lib/tmpfiles.d/ccnp.conf

add plugin for tdx device permission and ccnp UDS dir permission setting

---

deployment/script/image-manager.sh

The tool will build and publish CCNP docker images to a remote registry as user specified.

Add new image-manager for ccnp image build and publish

---

deployment/script/deploy-and-exec-ccnp-example.sh

refine shell script to replace registry and image tag according to user

example: refine shell script

---

deployment/README.md

* update the readme according to the shell script change

Doc: update doc for ccnp example usage

---

README.md

Add deployment guide link in README.md

README.md: add deployment guide link

---

test/e2e-test/ci-setup.sh

Modify file path and image version

---

test/e2e-test/ci-clean.sh

github ci: modify the image version in cleanup script

---

deployment/manifests/ccnp-node-measurement-example-deployment.yaml
deployment/script/deploy-and-exec-ccnp-example.sh

* add default prefix for example image
* increase script robustness

example: fix image name and example script

---

container/README.md

Add README.md to introduce docker images under container directory as well as how to build docker images.

Add README.md under container

---

test/e2e-test/ci-setup.sh

Update Dockefile directory for CI test setup.

ci-setup.sh: Update Dockerfile directory

---

device-plugin/ccnp-device-plugin/README.md

1. Use NFD release 0.14
2. Update content and format

Update device plugin document

---

tools/cvm-image-rewriter/README.md

Added additional dependencies for guestfs-tools for Debian distribution. Tested on Debian 10.

Update README.md: Added additional dependencies

---

.github/cspell.json
deployment/README.md
tools/cvm-image-rewriter/start-virt.sh
tools/cvm-image-rewriter/tdx-libvirt-ubuntu-host.xml.template

1. Add start-virt.sh and corresponding Libvirt XML template
2. Update CCNP deployment with details of booting TD

Add tools to boot TD using Libvirt

---

tools/cvm-image-rewriter/README.md
tools/cvm-image-rewriter/qemu-test.sh
tools/cvm-image-rewriter/run.sh

1. Update readme adding example usage and more details
2. Update default parameter value of qemu-test.sh

Update CVM image rewriter

---

deployment/script/deploy-ccnp.sh

Use release name instead of --generate-name and add uninstall commands to avoid helm installing multiple nfds：
NAME                                    NAMESPACE               REVISION
ccnp-device-plugin                      default                 1  
node-feature-discovery-1704942206       node-feature-discovery  1
node-feature-discovery-1704942408       node-feature-discovery  1

deploy-ccnp.sh: Update the NFD part of the script
